formform_homepage:
    path:     /
    defaults: { _controller: formformBundle:Default:index }

formform_personnes:
  path:    /personnes
  defaults: { _controller: formformBundle:Default:personnes}

formform_recapitulatif:
    path:    /recapitulatif
    defaults: { _controller: formformBundle:Default:recapitulatif}

formform_error:
  path:    /error
  defaults: { _ controller: formformBundle:Default:error}

formform_validation:
  path:    /validation
  defaults: { _controller: formformBundle:Default:validation}

formform_purge:
  path:    /purge
  defaults: { _controller: formformBundle:Default:purge}