services:
#    formform.example:
#        class: form\formBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    form_form.prix:
        class: form\formBundle\Prix\formPrix