<?php

namespace form\formBundle\Repository;

/**
 * commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getQuota($date)
	{
		$nbPlace=$this->createQueryBuilder('c')
		->SELECT('COUNT(c.nbPlace)')
		->WHERE('c.date=:date')
		->setParameter('date', $date)
		->getQuery()
		->getSingleScalarResult();

		return $nbPlace;
	}

}
