<?php

namespace form\formBundle\Repository;

/**
 * individuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class individuRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNbIndividu($date)
	{
		$nbIndividu=$this->createQueryBuilder('i')
		->SELECT('COUNT(i)')
		->leftJoin('i.commande_id', 'c')
		->WHERE('c.date=:date')
		->setParameter('date', $date)
		->getQuery()
		->getSingleScalarResult();

		return $nbIndividu;
	}
}
