<?php

namespace form\formBundle\Repository;

/**
 * individuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class individuRepository extends \Doctrine\ORM\EntityRepository
{
	public function getIndividu($commande)
	{
		$individu=$this->createQueryBuilder('i')
		->where('i.commande = :commande')
		->setParameter('commande', $commande)
		->getQuery()
		->getResult();

		return $individu;
	}
}
