<?php

namespace form\formBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * jourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jourRepository extends \Doctrine\ORM\EntityRepository
{
	public function getQuota($date)
	{
		$nbPlace=$this->createQueryBuilder('j')
		->WHERE('j.date=:date')
		->setParameter('date', $date)
		->getQuery()
		->getResult();

		return $nbPlace;
	}
}
